# TRM with Unified Grid Reasoning
# All modalities (text/image/grid) processed as 2D spatial grids

model_name: "TinyRecursiveReasoningModel_ACTV1"

# Grid-aware spatial reasoning
use_grid_reasoning: true
spatial_window_size: 3  # Local receptive field (like 3x3 convolution)

# Capsule configuration
hidden_size: 768
target_capsules: 12
num_concepts: 2048

# Grid structure
# For text: reshape sequence to 2D (e.g., 12 tokens -> 3x4 grid)
# For images: natural 2D patches (e.g., 16x16 patches)
# For ARC: native grid (variable size, up to 30x30)
grid_height: 4
grid_width: 3
max_grid_size: 30

# Architecture
num_heads: 8
L_layers: 6  # Spatial reasoning depth
H_cycles: 3
L_cycles: 2

# Multimodal training
use_semantic: true
encoder_model: "openai/clip-vit-large-patch14"
enable_quality_scoring: true

# DQN for action selection
enable_dqn: true
dqn_epsilon_start: 0.9
dqn_epsilon_end: 0.05
dqn_epsilon_decay: 10000
dqn_target_update_frequency: 100

# Output heads
use_vq_codebook: true
vq_codebook_size: 2048
vq_commitment_cost: 0.25

# Training
batch_size: 16
learning_rate: 3.0e-4
weight_decay: 0.1
warmup_steps: 500
gradient_clip: 1.0

# Deep supervision
enable_deep_supervision: true
supervision_steps: 3

# Memory (optional)
enable_memory: false
memory_capacity: 1024

# Multi-token prediction (optional)
enable_mtp: false
