# Text Generation Training Config
# Small-scale TRM for language modeling on local hardware

defaults:
  - arch: trm_text
  - _self_

hydra:
  output_subdir: null

# Data path
data_paths: ['data/text-wikitext2']
data_paths_test: []

evaluators: []  # Can add perplexity evaluator later

# Hyperparams - Training (scaled for local hardware)
global_batch_size: 32  # Small for 8GB RAM
epochs: 5000  # Extended for better convergence on small dataset
eval_interval: 25  # Check less frequently with more epochs
checkpoint_every_eval: True

# Learning rates
lr: 3e-4  # Standard for small LMs
lr_min_ratio: 0.1
lr_warmup_steps: 500

# Optimizer settings
beta1: 0.9
beta2: 0.95
weight_decay: 0.01  # Light regularization

# No puzzle embeddings for text
puzzle_emb_lr: 0.0
puzzle_emb_weight_decay: 0.0

seed: 42
min_eval_interval: 0

checkpoint_path: "checkpoints/text-trm-10m"

ema: False
ema_rate: 0.999
freeze_weights: False
